FactoryBot.define do

  factory :square do
    user_id               {"1"}
    name                  {"test"}
    zero                  {"test"}
    one                   {"test"}
    two                   {"test"}
    three                 {"test"}
    four                  {"test"}
    five                  {"test"}
    six                   {"test"}
    seven                 {"test"}
    eight                 {"test"}
    one_one               {"test"}
    one_two               {"test"}
    one_three             {"test"}
    one_four              {"test"}
    one_five              {"test"}
    one_six               {"test"}
    one_seven             {"test"}
    one_eight             {"test"}
    two_one               {"test"}
    two_two               {"test"}
    two_three             {"test"}
    two_four              {"test"}
    two_five              {"test"}
    two_six               {"test"}
    two_seven             {"test"}
    two_eight             {"test"}
    three_one             {"test"}
    three_two             {"test"}
    three_three           {"test"}
    three_four            {"test"}
    three_five            {"test"}
    three_six             {"test"}
    three_seven           {"test"}
    three_eight           {"test"}
    four_one              {"test"}
    four_two              {"test"}
    four_three            {"test"}
    four_four             {"test"}
    four_five             {"test"}
    four_six              {"test"}
    four_seven            {"test"}
    four_eight            {"test"}
    five_one              {"test"}
    five_two              {"test"}
    five_three            {"test"}
    five_four             {"test"}
    five_five             {"test"}
    five_six              {"test"}
    five_seven            {"test"}
    five_eight            {"test"}
    six_one               {"test"}
    six_two               {"test"}
    six_three             {"test"}
    six_four              {"test"}
    six_five              {"test"}
    six_six               {"test"}
    six_seven             {"test"}
    six_eight             {"test"}
    seven_one             {"test"}
    seven_two             {"test"}
    seven_three           {"test"}
    seven_four            {"test"}
    seven_five            {"test"}
    seven_six             {"test"}
    seven_seven           {"test"}
    seven_eight           {"test"}
    eight_one             {"test"}
    eight_two             {"test"}
    eight_three           {"test"}
    eight_four            {"test"}
    eight_five            {"test"}
    eight_six             {"test"}
    eight_seven           {"test"}
    eight_eight           {"test"}
  end

end
